import React from 'react';
import { PanelSection, PanelFooter, Button, Slider, Switch, Metric } from '../ui';
import { Wind, Play, Square } from 'lucide-react';
import { useStore } from '../components/Environment3D';

export default function WindTool({ regionBounds }) {
    const { 
        windSpeed, setWindSpeed, 
        windDirection, setWindDirection, 
        windComfortMetric, setWindComfortMetric,
        windParticleFlow, setWindParticleFlow,
        windSimRunning, setWindSimRunning,
        windSimBounds, setWindSimBounds,
        walkabilityAvgDist // repurposed generic stat variable to pass grid info
    } = useStore();

    return (
        <>
            <PanelSection>
                <div className="flex flex-col gap-6">
                    <Slider label="Wind Speed" min={0} max={30} step={1} value={windSpeed} onChange={setWindSpeed} suffix=" m/s" />
                    <Slider label="Wind Direction" min={0} max={360} step={5} value={windDirection} onChange={setWindDirection} suffix="°" />
                    <Slider label="Domain Width" min={100} max={1000} step={50} value={windSimBounds?.w || 300} onChange={(val) => setWindSimBounds({ ...windSimBounds, w: val })} suffix=" m" />
                    <Slider label="Domain Length" min={100} max={1000} step={50} value={windSimBounds?.d || 300} onChange={(val) => setWindSimBounds({ ...windSimBounds, d: val })} suffix=" m" />
                    <div className="flex flex-col gap-2 w-full">
                        <label className="text-[10px] font-semibold tracking-[0.1em] text-slate-500 uppercase">Comfort Metric</label>
                        <select 
                            value={windComfortMetric || 'speed'} 
                            onChange={(e) => setWindComfortMetric(e.target.value)}
                            className="bg-white shadow-sm border border-slate-200 rounded-xl px-4 py-2.5 text-xs text-slate-800 font-mono focus:outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-500/10 transition-all w-full cursor-pointer appearance-none"
                        >
                            <option value="speed">Raw Speed (Continuous)</option>
                            <option value="lawson">Lawson Criteria (Proxy)</option>
                            <option value="davenport">Davenport Criteria (Proxy)</option>
                            <option value="nen8100">NEN 8100 (Proxy)</option>
                            <option value="beaufort">Beaufort Scale</option>
                        </select>
                    </div>
                </div>
            </PanelSection>

            <PanelSection title="Simulation Engine">
                <div className="flex flex-col gap-3">
                    <p className="text-xs text-slate-500 leading-relaxed">
                        This module utilizes the ultra-fast <strong>Eddy3D Generative Adversarial Network (GAN)</strong>. It rasterizes the underlying building geometry and feeds the data into the local PyTorch ONNX surrogate model to predict wind flow instantaneously.
                    </p>
                    <p className="text-xs text-slate-500 leading-relaxed">
                        The outputs display a <strong>High-Resolution 2D Flow Map</strong> generated by the deep learning engine, dynamically suspended slightly above the architecture. It visualizes structural pressure nodes using an identical Turbo colormap.
                    </p>
                    {(!windComfortMetric || windComfortMetric === 'speed') && (
                        <div className="mt-1 flex flex-col gap-1.5 border border-slate-200/60 bg-white/50 p-2 rounded-lg">
                            <div className="flex justify-between text-[9px] uppercase font-bold text-slate-400 tracking-wider px-0.5">
                                <span className="text-blue-500">0 m/s (Block)</span>
                                <span className="text-emerald-500">Moderate</span>
                                <span className="text-red-500">High Gusts</span>
                            </div>
                            <div className="h-2 w-full rounded-full ring-1 ring-black/5" style={{ background: 'linear-gradient(to right, rgb(0,0,128), rgb(0,0,255), rgb(0,160,230), rgb(0,200,0), rgb(220,200,0), rgb(255,0,0))' }}></div>
                        </div>
                    )}
                    {windComfortMetric === 'lawson' && (
                        <div className="mt-1 flex flex-col gap-1 border border-slate-200/60 bg-white/50 p-2 rounded-lg text-[9px] uppercase font-bold text-slate-500">
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#0033ff]"></div> <span className="flex-1">Sitting (&lt; 4 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#00ccff]"></div> <span className="flex-1">Standing (&lt; 6 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#00cc00]"></div> <span className="flex-1">Strolling (&lt; 8 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#ffcc00]"></div> <span className="flex-1">Walking (&lt; 10 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#ff0000]"></div> <span className="flex-1 text-red-500">Uncomfortable (&gt; 10 m/s)</span></div>
                        </div>
                    )}
                    {windComfortMetric === 'davenport' && (
                        <div className="mt-1 flex flex-col gap-1 border border-slate-200/60 bg-white/50 p-2 rounded-lg text-[9px] uppercase font-bold text-slate-500">
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#0033ff]"></div> <span className="flex-1">Sitting (&lt; 3.6 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#00ccff]"></div> <span className="flex-1">Standing (&lt; 5.3 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#00cc00]"></div> <span className="flex-1">Walking (&lt; 7.6 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#ffcc00]"></div> <span className="flex-1">Fast Walk (&lt; 9.8 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#ff0000]"></div> <span className="flex-1 text-red-500">Dangerous (&gt; 9.8 m/s)</span></div>
                        </div>
                    )}
                    {windComfortMetric === 'nen8100' && (
                        <div className="mt-1 flex flex-col gap-1 border border-slate-200/60 bg-white/50 p-2 rounded-lg text-[9px] uppercase font-bold text-slate-500">
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#00cc00]"></div> <span className="flex-1">Comfortable (&lt; 5 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#ff8000]"></div> <span className="flex-1">Moderate (5 - 15 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#ff0000]"></div> <span className="flex-1 text-red-500">Dangerous (&gt; 15 m/s)</span></div>
                        </div>
                    )}
                    {windComfortMetric === 'beaufort' && (
                        <div className="mt-1 flex flex-col gap-1 border border-slate-200/60 bg-white/50 p-2 rounded-lg text-[9px] uppercase font-bold text-slate-500">
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#808080]"></div> <span className="flex-1">Calm (&lt; 0.5 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#6699cc]"></div> <span className="flex-1">Light Air (&lt; 1.5 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#3399ff]"></div> <span className="flex-1">Light Breeze (&lt; 3.3 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#00cccc]"></div> <span className="flex-1">Gentle Breeze (&lt; 5.5 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#00cc00]"></div> <span className="flex-1">Moderate (&lt; 7.9 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#ffff00]"></div> <span className="flex-1">Fresh (&lt; 10.7 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#ff8000]"></div> <span className="flex-1 text-orange-500">Strong (&lt; 13.8 m/s)</span></div>
                            <div className="flex items-center gap-2"><div className="w-3 h-3 rounded-sm bg-[#ff0000]"></div> <span className="flex-1 text-red-500">Gale (&gt; 13.8 m/s)</span></div>
                        </div>
                    )}
                </div>
            </PanelSection>

            <PanelSection title="Simulation Data" className="flex-1">
                <div className="flex flex-col gap-1">
                    <Metric label="Status" value={windSimRunning ? (walkabilityAvgDist?.includes?.('Predict') ? "COMPLETED" : "COMPUTING") : "AWAITING COMPUTE"} highlight={windSimRunning} />
                    <Metric label="Grid Memory" value={windSimRunning ? walkabilityAvgDist : "--"} />
                </div>
            </PanelSection>

            <PanelFooter>
                <Button variant={windSimRunning ? (walkabilityAvgDist?.includes?.('Predict') ? "secondary" : "danger") : "primary"} className="w-full py-3" onClick={() => {
                    if (windSimRunning) {
                        setWindSimRunning(false);
                        useStore.getState().setWalkabilityStats({ walkabilityAvgDist: null });
                    } else {
                        setWindSimRunning(true);
                        useStore.getState().setWalkabilityStats({ walkabilityAvgDist: 'Initializing...' });
                    }
                }}>
                    {windSimRunning ? <Square size={16} fill="currentColor" /> : <Play size={16} fill="currentColor" />} 
                    {windSimRunning ? (walkabilityAvgDist?.includes?.('Predict') ? 'Clear Simulation' : 'Stop Simulation') : 'Execute'}
                </Button>
            </PanelFooter>
        </>
    );
}
