import React from 'react';
import { PanelSection, PanelFooter, Button, Slider, Switch, Metric } from '../ui';
import { Wind, Play, Square } from 'lucide-react';
import { useStore } from '../components/Environment3D';

export default function WindTool({ regionBounds }) {
    const { 
        windSpeed, setWindSpeed, 
        windDirection, setWindDirection, 
        windParticleFlow, setWindParticleFlow,
        windSimRunning, setWindSimRunning,
        walkabilityAvgDist // repurposed generic stat variable to pass grid info
    } = useStore();

    return (
        <>
            <PanelSection>
                <div className="flex flex-col gap-6">
                    <Slider label="Base Wind Velocity" min={0} max={30} step={1} value={windSpeed} onChange={setWindSpeed} suffix=" m/s" />
                    <Slider label="Wind Direction" min={0} max={360} step={5} value={windDirection} onChange={setWindDirection} suffix="°" />
                </div>
            </PanelSection>

            <PanelSection title="Simulation Engine">
                <div className="flex flex-col gap-3">
                    <p className="text-xs text-slate-500 leading-relaxed">
                        This module utilizes the ultra-fast <strong>Eddy3D Generative Adversarial Network (GAN)</strong>. It rasterizes the underlying building geometry and feeds the data into the local PyTorch ONNX surrogate model to predict wind flow instantaneously.
                    </p>
                    <p className="text-xs text-slate-500 leading-relaxed">
                        The outputs display a <strong>High-Resolution 2D Flow Map</strong> generated by the deep learning engine, dynamically suspended slightly above the architecture. It visualizes structural pressure nodes using an identical Turbo colormap.
                    </p>
                    <div className="mt-1 flex flex-col gap-1.5 border border-slate-200/60 bg-white/50 p-2 rounded-lg">
                        <div className="flex justify-between text-[9px] uppercase font-bold text-slate-400 tracking-wider px-0.5">
                            <span className="text-blue-500">0 m/s (Block)</span>
                            <span className="text-emerald-500">Moderate</span>
                            <span className="text-red-500">High Gusts</span>
                        </div>
                        <div className="h-2 w-full rounded-full ring-1 ring-black/5" style={{ background: 'linear-gradient(to right, rgb(0,0,128), rgb(0,0,255), rgb(0,160,230), rgb(0,200,0), rgb(220,200,0), rgb(255,0,0))' }}></div>
                    </div>
                </div>
            </PanelSection>

            <PanelSection title="Simulation Data" className="flex-1">
                <div className="flex flex-col gap-1">
                    <Metric label="Status" value={windSimRunning ? (walkabilityAvgDist?.includes?.('Predict') ? "COMPLETED" : "COMPUTING") : "AWAITING COMPUTE"} highlight={windSimRunning} />
                    <Metric label="Grid Memory" value={windSimRunning ? walkabilityAvgDist : "--"} />
                </div>
            </PanelSection>

            <PanelFooter>
                <Button variant={windSimRunning ? (walkabilityAvgDist?.includes?.('Predict') ? "secondary" : "danger") : "primary"} className="w-full py-3" onClick={() => {
                    if (windSimRunning) {
                        setWindSimRunning(false);
                        useStore.getState().setWalkabilityStats({ walkabilityAvgDist: null });
                    } else {
                        setWindSimRunning(true);
                        useStore.getState().setWalkabilityStats({ walkabilityAvgDist: 'Initializing...' });
                    }
                }}>
                    {windSimRunning ? <Square size={16} fill="currentColor" /> : <Play size={16} fill="currentColor" />} 
                    {windSimRunning ? (walkabilityAvgDist?.includes?.('Predict') ? 'Clear Simulation' : 'Stop Simulation') : 'Execute'}
                </Button>
            </PanelFooter>
        </>
    );
}
